name = "UnpoweredLandingsPaper"
uuid = "d01a3adb-daf7-4528-a80f-8345950758df"
version = "0.1.0"
authors = ["tom <tom.rottier@manchester.ac.uk>"]

[workspace]
projects = ["scripts"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPMumps = "3b83494e-c0a4-4895-918b-9157a7a085a1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
PointMass = "cef08b25-cf8f-4213-b67e-f952c602b589"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[sources]
Makie = {subdir = "Makie", url = "https://github.com/TomRottier/Makie.jl"}
PointMass = {path = "lib\\PointMass.jl"}

[compat]
CairoMakie = "0.15.6"
ColorSchemes = "3.31.0"
DelimitedFiles = "1.9.1"
Folds = "0.2.10"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
MadNLP = "0.8.12"
MadNLPMumps = "0.5.1"
NLPModelsIpopt = "0.10.4"
NonlinearSolve = "4.10.0"
OptimalControl = "1.1.1"
OrdinaryDiffEqTsit5 = "1.5.0"
QuadGK = "2.11.2"
